// <auto-generated />
using System;
using CinemasTheBESTia.Booking.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CinemasTheBESTia.Booking.Data.Context.Migrations
{
    [DbContext(typeof(BookingDbContext))]
    partial class BookingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CinemasTheBESTia.Entities.CinemaFunctions.CinemaFunction", b =>
                {
                    b.Property<int>("CinemaFuctionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FunctionDate");

                    b.Property<DateTime>("FunctionTime");

                    b.Property<string>("OriginalMovieTitle");

                    b.HasKey("CinemaFuctionId");

                    b.ToTable("CinemaFunctions");
                });
#pragma warning restore 612, 618
        }
    }
}
